NumPy Retail Analytics Assignment
Business Scenario
You are working as a Data Analyst for SmartMart Retail Stores. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

sales_data — monthly sales revenue generated by each store for different product categories.
cost_data — total cost incurred by each store for the same product categories.


Part 1: Dataset Creation

In [16]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding

Question 1: Array Dimensions
The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data
Shape of sales_data
Total number of values
Data type of the array
Memory occupied by the array

In [13]:
import numpy as np

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

print("Number of dimensions:", sales_data.ndim)
print("Shape:", sales_data.shape)
print("Total number of values:", sales_data.size)
print("Data type:", sales_data.dtype)
print("Memory occupied:", sales_data.nbytes, "memory occupied")

Number of dimensions: 2
Shape: (5, 6)
Total number of values: 30
Data type: int32
Memory occupied: 120 memory occupied


Question 2: Store and Category Count
Calculate the following:

Total number of stores
Total number of product categories
Total number of store-category combinations

In [ ]:
total_stores = len(stores)
total_categories = len(categories)
total_combinations = total_stores * total_categories
print("Total number of stores:", total_stores)
print("Total number of product categories:", total_categories)
print("Total number of store-category combinations:", total_combinations)

NameError: name 'stores' is not defined

Question 3: Sales Data Type Conversion
The reporting application requires sales values in floating-point format.

Convert sales_data into:

float32
float64
Compare the memory used by both arrays.

In [18]:
sales_float32 = sales_data.astype(np.float32)
sales_float64 = sales_data.astype(np.float64)
print("Float32 memory:", sales_float32.nbytes, "bytes")
print("Float64 memory:", sales_float64.nbytes, "bytes")

Float32 memory: 120 bytes
Float64 memory: 240 bytes


Part 3: Indexing and Data Extraction

Question 4: Bengaluru Store Analysis
The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

In [19]:
bengaluru_sales = sales_data[0]
print("bengaluru sales:", bengaluru_sales)

bengaluru sales: [850000 420000 310000 275000 190000 225000]


Question 5: Mumbai Cost Analysis
Extract the total cost incurred by the Mumbai store for all product categories.

In [20]:
mumbai_cost = cost_data[0]
print("mumbai cost :", mumbai_cost)

mumbai cost : [640000 315000 220000 205000 125000 160000]


Question 6: Electronics Sales Across Stores
The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data.

In [21]:
electronics_sales = sales_data[:, 0]
print("Electronics sales:", electronics_sales)

Electronics sales: [ 850000  780000  920000 1050000  690000]


Question 7: Clothing Cost Across Stores
Extract the Clothing cost for every store from cost_data.

In [22]:
clothing_cost = cost_data[:,2]
print("clothing cost:", clothing_cost)

clothing cost: [220000 210000 245000 265000 205000]


Question 8: Hyderabad Furniture Performance
Find the following for Hyderabad:

Furniture sales
Furniture cost
Furniture profit

In [ ]:
furniture_sales = sales_data[1, 3]
furniture_cost = cost_data[1, 3]
furniture_profit = furniture_sales - furniture_cost

print("Furniture sales:", furniture_sales)
print("Furniture cost:", furniture_cost)
print("Furniture profit:", furniture_profit)

Furniture sales: 310000
Furniture cost: 225000
Furniture profit: 85000


Question 9: Chennai Category Range
Extract Chennai’s sales for the following categories:

Groceries
Clothing
Furniture
Use array slicing.

In [24]:
chennai_sales = sales_data[2, 1:4]
print("Chennai sales:", chennai_sales)

Chennai sales: [390000 340000 260000]


Question 10: Selected Store Analysis
Extract sales data for:

Bengaluru
Chennai
Pune
Include only:

Electronics
Clothing
Beauty
Use advanced indexing.

In [25]:
selected_sales = sales_data[[0, 2, 4]][:, [0, 2, 4]]
print("Selected sales:")
print(selected_sales)

Selected sales:
[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


# NumPy Retail Analytics Assignment


Question 11: Company-Wide Sales
Calculate the total sales revenue generated by all stores and all categories.

In [15]:
total_sales=np.sum(sales_data)
print(total_sales)

11675000


Question 12: Store-Wise Sales
Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales

In [27]:
store_sales = sales_data.sum(axis=1); exec("for store, sales in zip(stores, store_sales):\n    print(store, ':', sales)")

Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000
Pune : 1980000


Question 13: Category-Wise Sales
Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [26]:
category_sales = sales_data.sum(axis=0); exec("for category, sales in zip(categories, category_sales):\n    print(category, ':', sales)")

Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Beauty : 1010000
Sports : 1175000


Question 14: Average Sales Per Store
Calculate the average sales generated by each store across all six product categories.

In [31]:
average_sales = sales_data.mean(axis=1); exec("for i in range(5): print(stores[i], ':', round(average_sales[i], 2))")

Bengaluru : 378333.33
Hyderabad : 382500.0
Chennai : 385000.0
Mumbai : 470000.0
Pune : 330000.0


Question 15: Average Sales Per Category
Calculate the average sales of each product category across the five stores.

In [29]:
average_category = sales_data.mean(axis=0)
print(*[f"{categories[i]}: {round(average_category[i], 2)}" for i in range(6)], sep="\n")

Electronics: 858000.0
Groceries: 437000.0
Clothing: 320000.0
Furniture: 283000.0
Beauty: 202000.0
Sports: 235000.0


Question 16: Highest-Selling Store
Identify:

Index of the store with the highest total sales
Name of the store
Total sales generated by that store
Use np.argmax().

In [32]:
store_sales = sales_data.sum(axis=1)
index = np.argmax(store_sales)

print("Index:", index)
print("Store:", stores[index])
print("Total sales:", store_sales[index])

Index: 3
Store: Mumbai
Total sales: 2820000


Question 17: Lowest-Selling Store
Identify the store with the lowest overall sales.

Use np.argmin().

In [34]:
store_sales = sales_data.sum(axis=1)
index = np.argmin(store_sales)

print("Index:", index)
print("Store:", stores[index])
print("Total sales:", store_sales[index])

Index: 4
Store: Pune
Total sales: 1980000


Question 18: Highest-Selling Category
Find the product category that generated the highest total sales across the company.

In [35]:
category_sales = sales_data.sum(axis=0)
index = np.argmax(category_sales)

print("Index:", index)
print("Category:", categories[index])
print("Total sales:", category_sales[index])

Index: 0
Category: Electronics
Total sales: 4290000


Question 19: Lowest-Selling Category
Find the product category with the lowest total sales across all stores.

In [36]:
category_sales = sales_data.sum(axis=0)
index = np.argmin(category_sales)

print("Index:", index)
print("Category:", categories[index])
print("Total sales:", category_sales[index])

Index: 4
Category: Beauty
Total sales: 1010000


Part 5: Cost Analysis
Question 20: Total Company Cost
Calculate the total cost incurred by SmartMart across all stores and product categories.

In [37]:
total_cost = cost_data.sum()
print("Total company cost:", total_cost)

Total company cost: 8600000


Question 21:Store-Wise Cost 
Calculate the total cost incurred by each store.

In [40]:
store_cost = cost_data.sum(axis=1)
print("Bengaluru:", store_cost[0])
print("Hyderabad:", store_cost[1])
print("Chennai:", store_cost[2])
print("Mumbai:", store_cost[3])
print("Pune:", store_cost[4])

Bengaluru: 1665000
Hyderabad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000


Question 22: Category-Wise Cost
Calculate the total cost incurred for each product category across all stores.

In [41]:
category_cost = cost_data.sum(axis=0)
print("Electronics:", category_cost[0])
print("Groceries:", category_cost[1])
print("Clothing:", category_cost[2])
print("Furniture:", category_cost[3])
print("Beauty:", category_cost[4])
print("Sports:", category_cost[5])

Electronics: 3250000
Groceries: 1660000
Clothing: 1145000
Furniture: 1045000
Beauty: 665000
Sports: 835000


Question 23: Most Expensive Store
Identify the store with the highest total operating cost.

In [42]:
store_cost = cost_data.sum(axis=1)
index = np.argmax(store_cost)

print("Index:", index)
print("Store:", stores[index])
print("Total cost:", store_cost[index])

Index: 3
Store: Mumbai
Total cost: 2065000


Question 24: Lowest-Cost Store
Identify the store with the lowest total cost.

In [43]:
store_cost = cost_data.sum(axis=1)
index = np.argmin(store_cost)

print("Index:", index)
print("Store:", stores[index])
print("Total cost:", store_cost[index])

Index: 4
Store: Pune
Total cost: 1475000


Question 25: Most Expensive Product Category
Determine which product category has the highest total cost across all stores.

In [44]:
category_cost = cost_data.sum(axis=0)
print("Most expensive category:", categories[np.argmax(category_cost)], "Cost:", category_cost.max())

Most expensive category: Electronics Cost: 3250000


Part 6: Profit Analysis Using Two Arrays
Question 26: Profit Matrix
Calculate the profit generated for every store and product category.

Use:

profit_data = sales_data - cost_data
Display the complete profit matrix.

In [45]:
profit_data = sales_data - cost_data
print(profit_data)

[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


Question 27: Store-Wise Profit
Calculate the total profit generated by each store.

In [50]:
store_profit = profit_data.sum(axis=1)
print("Bengaluru:", store_profit[0], "\nHyderabad:", store_profit[1], "\nChennai:", store_profit[2], "\nMumbai:", store_profit[3], "\nPune:", store_profit[4])

Bengaluru: 605000 
Hyderabad: 610000 
Chennai: 600000 
Mumbai: 755000 
Pune: 505000


Question 28: Category-Wise Profit
Calculate the total profit generated by each product category.

In [51]:
category_profit = profit_data.sum(axis=0)
print("Electronics:", category_profit[0], "\nGroceries:", category_profit[1], "\nClothing:", category_profit[2], "\nFurniture:", category_profit[3], "\nBeauty:", category_profit[4], "\nSports:", category_profit[5])

Electronics: 1040000 
Groceries: 525000 
Clothing: 455000 
Furniture: 370000 
Beauty: 345000 
Sports: 340000


Question 29: Most Profitable Store
Identify the store that generated the highest total profit.

Display:

Store name
Total sales
Total cost
Total profit

In [53]:
store_profit = profit_data.sum(axis=1)
i = np.argmax(store_profit)
print("Store:", stores[i], "\nSales:", sales_data.sum(axis=1)[i], "\nCost:", cost_data.sum(axis=1)[i], "\nProfit:", store_profit[i])

Store: Mumbai 
Sales: 2820000 
Cost: 2065000 
Profit: 755000


Question 30: Least Profitable Store
Identify the store that generated the lowest total profit.

In [54]:
store_profit = profit_data.sum(axis=1)
i = np.argmin(store_profit); print("Store:", stores[i], "\nSales:", sales_data.sum(axis=1)[i], "\nCost:", cost_data.sum(axis=1)[i], "\nProfit:", store_profit[i])

Store: Pune 
Sales: 1980000 
Cost: 1475000 
Profit: 505000


Question 31: Most Profitable Category
Find the category with the highest total profit across all stores.

In [55]:
category_profit = profit_data.sum(axis=0)
i = np.argmax(category_profit); print("Category:", categories[i], "\nTotal profit:", category_profit[i])

Category: Electronics 
Total profit: 1040000


Question 32: Least Profitable Category
Find the category with the lowest total profit.

In [56]:
category_profit = profit_data.sum(axis=0)
i = np.argmin(category_profit); print("Category:", categories[i], "\nTotal profit:", category_profit[i])

Category: Sports 
Total profit: 340000


Question 33: Maximum Individual Profit
Find the highest profit generated by any single store-category combination.

Display:

Profit amount
Store name
Product category
Use np.unravel_index().

In [57]:
i = np.unravel_index(np.argmax(profit_data), profit_data.shape)
print("Profit:", profit_data[i], "\nStore:", stores[i[0]], "\nCategory:", categories[i[1]])

Profit: 260000 
Store: Mumbai 
Category: Electronics


Question 34: Minimum Individual Profit
Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [58]:
i = np.unravel_index(np.argmin(profit_data), profit_data.shape)
print("Profit:", profit_data[i], "\nStore:", stores[i[0]], "\nCategory:", categories[i[1]])

Profit: 55000 
Store: Pune 
Category: Furniture


Part 7: Profit Margin Analysis
Question 35: Profit Margin Matrix
Calculate the profit margin percentage for every store-category combination.

Use:

profit_margin = (profit_data / sales_data) * 100
Round the result to two decimal places.

In [59]:
profit_margin = (profit_data / sales_data) * 100
print(np.round(profit_margin, 2))

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


Question 36: Store-Wise Profit Margin
Calculate the overall profit margin percentage for each store using:

Store Profit Margin =
Total Store Profit / Total Store Sales × 100

In [60]:
store_sales=sales_data.sum(axis=1)
stores_profits=profit_data.sum(axis=1)
print(np.round((store_profit/store_sales)*100,2))

[26.65 26.58 25.97 26.77 25.51]


Question 37: Category-Wise Profit Margin
Calculate the overall profit margin percentage for each product category.

In [62]:
margin = np.round((category_profit / sales_data.sum(axis=0)) * 100, 2); print("Electronics:", margin[0], "\nGroceries:", margin[1], "\nClothing:", margin[2], "\nFurniture:", margin[3], "\nBeauty:", margin[4], "\nSports:", margin[5])

Electronics: 24.24 
Groceries: 24.03 
Clothing: 28.44 
Furniture: 26.15 
Beauty: 34.16 
Sports: 28.94


Question 38: Best Store by Profit Margin
Identify the store with the highest overall profit margin.

In [63]:
store_margin = (store_profit / store_sales) * 100
i = np.argmax(store_margin); print("Store:", stores[i], "\nProfit Margin:", round(store_margin[i], 2), "%")

Store: Mumbai 
Profit Margin: 26.77 %


Question 39: Best Category by Profit Margin
Identify the product category with the highest profit margin.

In [64]:
category_margin = (category_profit / sales_data.sum(axis=0)) * 100
i = np.argmax(category_margin); print("Category:", categories[i], "\nProfit Margin:", round(category_margin[i], 2), "%")

Category: Beauty 
Profit Margin: 34.16 %



Question 40: Low-Margin Transactions
Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store
Category
Sales
Cost
Profit
Profit margin
Use Boolean indexing.



In [69]:
rows, cols = np.where(profit_margin < 22)
for r, c in zip(rows, cols):
    print(stores[r], categories[c], sales_data[r,c], cost_data[r,c], profit_data[r,c], round(profit_margin[r,c], 2))

In [74]:
profit_margin = (profit_data / sales_data) * 100
low_margin = profit_margin < 22

print("Low-margin transactions:", np.sum(low_margin))

Low-margin transactions: 0


Part 8: Boolean Filtering
Question 41: High Sales Values
Find all sales values greater than ₹5,00,000.

In [8]:
high_sales = sales_data[sales_data > 500000]
print(high_sales)

[ 850000  780000  920000 1050000  510000  690000]


Question 42: Low Sales Values
Find all sales values below ₹2,00,000.

In [24]:
low_sales = sales_data[sales_data < 200000]
print(low_sales)

[190000 185000 175000]


Question 43: High Profit Values
Find all store-category combinations where profit is greater than ₹1,50,000.

In [34]:
high_profit = profit_data[profit_data > 150000]
print(high_profit)

[210000 190000 220000 260000 160000]


Question 44: Moderate Sales Range
Find sales values between ₹2,50,000 and ₹5,00,000.

Use np.logical_and().

In [28]:
moderate_sales = sales_data[np.logical_and(sales_data >= 250000, sales_data <= 500000)]
print(moderate_sales)

[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


Question 45: Premium Performance
A store-category combination is considered premium when:

Sales are greater than ₹5,00,000
Profit is greater than ₹1,50,000
Find all premium-performing combinations.

In [31]:
premium = np.logical_and(sales_data > 500000, profit_data > 150000)
print(sales_data[premium])

[ 850000  780000  920000 1050000  690000]


Question 46: Underperforming Combinations
A store-category combination is considered underperforming when:

Sales are below ₹2,50,000
Profit margin is below 25%
Find all such combinations.

In [36]:
profit_margin = (profit_data / sales_data) * 100
underperforming = np.logical_and(sales_data < 250000, profit_margin < 25)
print(sales_data[underperforming])

[225000]


Question 47: Category Performance Classification
Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000
"Medium" when sales are between ₹2,50,000 and ₹4,99,999
"Low" when sales are below ₹2,50,000
Use np.where() or np.select().

In [37]:
conditions = [sales_data >= 500000, sales_data >= 250000]
choices = ["High", "Medium"]

sales_level = np.select(conditions, choices, default="Low")
print(sales_level)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


Part 9: Target-Based Analysis
Use the following category-wise monthly sales targets:

sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

Question 48: Target Comparison
Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.

In [38]:
sales_targets = np.array([800000, 450000, 300000, 280000, 200000, 220000])
comparison = sales_data >= sales_targets
print(comparison)

[[ True False  True False False  True]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 49: Target Achievement Matrix
Create a Boolean array where:

True means the store achieved the category target
False means the store failed to achieve the target

In [39]:
target_achieved = sales_data >= sales_targets
print(target_achieved)

[[ True False  True False False  True]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 50: Target Achievement Count
Calculate the number of categories in which each store achieved its target.

In [40]:
target_count = target_achieved.sum(axis=1)
print(target_count)

[3 4 2 6 0]


Question 51: Best Target-Performing Store
Find the store that achieved the highest number of category targets.

In [41]:
i = np.argmax(target_count)
print("Store:", stores[i], "\nTargets achieved:", target_count[i])

Store: Mumbai 
Targets achieved: 6


Question 52: Target Achievement by Category
Calculate how many stores achieved the target for each product category.

In [42]:
category_target_count = target_achieved.sum(axis=0)
print(category_target_count)

[3 2 3 2 2 3]


Question 53: Sales Target Variance
Calculate the difference between actual sales and target sales for every store.

Use:

Variance = Actual Sales - Target Sales

In [43]:
sales_variance = sales_data - sales_targets
print(sales_variance)

[[  50000  -30000   10000   -5000  -10000    5000]
 [ -20000   10000   -5000   30000   10000   20000]
 [ 120000  -60000   40000  -20000  -15000   -5000]
 [ 250000   60000   75000   65000   50000   70000]
 [-110000  -45000  -20000  -55000  -25000  -15000]]


Question 54: Percentage Above or Below Target
Calculate the percentage variance from the target using:

Percentage Variance =
(Actual Sales - Target Sales) / Target Sales × 100

In [44]:
percentage_variance = ((sales_data - sales_targets) / sales_targets) * 100
print(np.round(percentage_variance, 2))

[[  6.25  -6.67   3.33  -1.79  -5.     2.27]
 [ -2.5    2.22  -1.67  10.71   5.     9.09]
 [ 15.   -13.33  13.33  -7.14  -7.5   -2.27]
 [ 31.25  13.33  25.    23.21  25.    31.82]
 [-13.75 -10.    -6.67 -19.64 -12.5   -6.82]]


Question 55: Stores Missing Electronics Target
Identify stores that failed to achieve the Electronics sales target.

In [45]:
failed = sales_data[:, 0] < sales_targets[0]
print(stores[failed])

['Hyderabad' 'Pune']


Question 56: Stores Achieving All Targets
Check whether any store achieved its target in all six product categories.

Use np.all().

In [46]:
all_targets = np.all(target_achieved, axis=1)
print(stores[all_targets])

['Mumbai']


Question 57: Stores Achieving At Least One Target
Identify stores that achieved at least one category target.

Use np.any().

In [47]:
one_target = np.any(target_achieved, axis=1)
print(stores[one_target])

['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


Part 10: Discount Scenario
SmartMart plans to offer category-wise discounts:

discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [48]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

Question 58: Discount Amount Matrix
Calculate the discount amount for each store-category combination.

Use broadcasting.

In [49]:
discount_rates = np.array([0.10, 0.05, 0.15, 0.12, 0.08, 0.10])
discount_amount = sales_data * discount_rates
print(discount_amount)

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


Question 59: Sales After Discount
Calculate the net sales value after applying the category-wise discounts.

In [50]:
sales_after_discount = sales_data - discount_amount
print(sales_after_discount)

[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


Question 60: Profit After Discount
Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

In [51]:
profit_after_discount = sales_after_discount - cost_data
print(profit_after_discount)

[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


Question 61: Profit Margin After Discount
Calculate the new profit margin after applying discounts.

In [52]:
profit_margin_after_discount = (profit_after_discount / sales_after_discount) * 100
print(np.round(profit_margin_after_discount, 2))

[[16.34 21.05 16.51 15.29 28.49 20.99]
 [15.95 19.91 16.25 17.52 27.54 21.3 ]
 [15.46 20.38 15.22 14.77 29.49 19.9 ]
 [16.4  19.5  16.86 17.65 28.26 21.46]
 [14.65 19.43 13.87 14.14 28.57 21.41]]


Question 62: Loss-Making Transactions
Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

In [53]:
print(np.any(profit_after_discount < 0))

False


Question 63: Discount Impact
Calculate how much total revenue the company loses because of the proposed discounts.

In [54]:
revenue_loss = discount_amount.sum()
print("Total revenue loss:", revenue_loss)

Total revenue loss: 1146350.0


Question 64: Store Most Affected by Discounts
Identify the store that loses the highest amount of revenue due to discounts.

In [55]:
store_loss = discount_amount.sum(axis=1)
i = np.argmax(store_loss)

print("Store:", stores[i])
print("Revenue loss:", store_loss[i])

Store: Mumbai
Revenue loss: 277150.0


Part 11: Tax and Price Adjustment
The government introduces category-wise tax rates:

tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])
Question 65: Tax Collection Matrix
Calculate the tax collected on sales for each store and category.

In [56]:

tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

In [57]:
tax_rates = np.array([0.18, 0.05, 0.12, 0.18, 0.18, 0.12])
tax_collection = sales_data * tax_rates
print(tax_collection)

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


Question 66: Sales Including Tax
Calculate the final customer billing value after adding tax.

In [58]:
sales_with_tax = sales_data + tax_collection
print(sales_with_tax)

[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


Question 67: Store-Wise Tax Collection
Calculate the total tax collected by each store.

In [59]:
store_tax = tax_collection.sum(axis=1)

print("Bengaluru:", store_tax[0])
print("Hyderabad:", store_tax[1])
print("Chennai:", store_tax[2])
print("Mumbai:", store_tax[3])
print("Pune:", store_tax[4])

Bengaluru: 321900.0
Hyderabad: 321200.0
Chennai: 331800.0
Mumbai: 401400.0
Pune: 274650.0


Question 68: Category-Wise Tax Collection
Calculate total tax collected for each category.

In [60]:
category_tax = tax_collection.sum(axis=0)

print("Electronics:", category_tax[0])
print("Groceries:", category_tax[1])
print("Clothing:", category_tax[2])
print("Furniture:", category_tax[3])
print("Beauty:", category_tax[4])
print("Sports:", category_tax[5])

Electronics: 772200.0
Groceries: 109250.0
Clothing: 192000.0
Furniture: 254700.0
Beauty: 181800.0
Sports: 141000.0


Question 69: Highest Tax-Contributing Store
Identify the store that contributes the highest tax amount.

In [61]:
store_tax = tax_collection.sum(axis=1)
i = np.argmax(store_tax)

print("Store:", stores[i])
print("Tax:", store_tax[i])

Store: Mumbai
Tax: 401400.0


Part 12: Array Modification
Question 70: Updated Pune Electronics Sales
The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [62]:
updated_sales = sales_data.copy()
updated_sales[4, 0] = 740000
print(updated_sales)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]


Question 71: Revised Beauty Cost
Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [63]:
updated_cost = cost_data.copy()
updated_cost[:, 4] = updated_cost[:, 4] * 0.92
print(updated_cost)

[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


Question 72: Furniture Cost Increase
Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [64]:
updated_cost = cost_data.copy()
updated_cost[:, 3] = updated_cost[:, 3] * 1.12
print(updated_cost)

[[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


Question 73: Store Closure Simulation
Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete().

In [65]:
new_sales = np.delete(sales_data, 4, axis=0)
new_cost = np.delete(cost_data, 4, axis=0)

print(new_sales)
print(new_cost)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


Question 74: Adding a New Store
A new Delhi store is opened with the following data:

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
Add Delhi to both arrays using np.vstack().

Also add "Delhi" to the stores array.

In [66]:
delhi_sales = np.array([880000, 475000, 330000, 290000, 215000, 250000])
delhi_cost = np.array([665000, 360000, 235000, 215000, 145000, 180000])
new_sales = np.vstack((sales_data, delhi_sales))
new_cost = np.vstack((cost_data, delhi_cost))
new_stores = np.append(stores, "Delhi")

print(new_stores)
print(new_sales)
print(new_cost)

['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]


Question 75: Adding a New Product Category
SmartMart starts selling Home Appliances.

home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
Add the new category as a column using np.column_stack() or np.hstack().

In [67]:
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])

In [68]:
home_appliance_sales = np.array([360000, 325000, 390000, 420000, 295000])
home_appliance_cost = np.array([265000, 240000, 285000, 305000, 225000])
new_sales = np.column_stack((sales_data, home_appliance_sales))
new_cost = np.column_stack((cost_data, home_appliance_cost))

print(new_sales)
print(new_cost)

[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]


Part 13: Sorting and Ranking
Question 76: Sort Stores by Sales
Sort stores in ascending order based on total sales.

Display store names and sales totals.

In [69]:
store_sales = sales_data.sum(axis=1)
i = np.argsort(store_sales)

print(stores[i])
print(store_sales[i])

['Pune' 'Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']
[1980000 2270000 2295000 2310000 2820000]


Question 77: Rank Stores by Profit
Rank stores from highest to lowest total profit.

Use np.argsort().

In [70]:
store_profit = profit_data.sum(axis=1)
i = np.argsort(store_profit)[::-1]
print(stores[i])
print(store_profit[i])

['Mumbai' 'Hyderabad' 'Bengaluru' 'Chennai' 'Pune']
[755000 610000 605000 600000 505000]


Question 78: Sort Categories by Revenue
Sort product categories from highest to lowest total revenue.

In [71]:
category_sales = sales_data.sum(axis=0)
i = np.argsort(category_sales)[::-1]
print(categories[i])
print(category_sales[i])

['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Sports' 'Beauty']
[4290000 2185000 1600000 1415000 1175000 1010000]


Question 79: Top Three Store-Category Sales
Find the three highest individual sales values in the complete sales matrix.

Display their:

Sales value
Store name
Category name

In [74]:
top_sales = np.argsort(sales_data.flatten())[-3:][::-1]
for i in top_sales:
    row, col = np.unravel_index(i, sales_data.shape)
    print("Sales:", sales_data[row, col], "Store:", stores[row], "Category:", categories[col])

Sales: 1050000 Store: Mumbai Category: Electronics
Sales: 920000 Store: Chennai Category: Electronics
Sales: 850000 Store: Bengaluru Category: Electronics


Question 80: Bottom Three Profits
Find the three lowest profit values in the profit matrix.

In [73]:
lowest = np.argsort(profit_data.flatten())[:3]
for i in lowest:
    row, col = np.unravel_index(i, profit_data.shape)
    print("Profit:", profit_data[row, col])
    print("Store:", stores[row])
    print("Category:", categories[col])
    print()

Profit: 55000
Store: Pune
Category: Furniture

Profit: 60000
Store: Pune
Category: Sports

Profit: 60000
Store: Pune
Category: Beauty



Part 14: Statistical Analysis
Question 81: Sales Statistics
Calculate the following for the complete sales array:

Minimum
Maximum
Mean
Median
Standard deviation
Variance
25th percentile
50th percentile
75th percentile


In [75]:
print("Minimum:", np.min(sales_data))
print("Maximum:", np.max(sales_data))
print("Mean:", np.mean(sales_data))
print("Median:", np.median(sales_data))
print("Standard deviation:", np.std(sales_data))
print("Variance:", np.var(sales_data))
print("25th percentile:", np.percentile(sales_data, 25))
print("50th percentile:", np.percentile(sales_data, 50))
print("75th percentile:", np.percentile(sales_data, 75))

Minimum: 175000
Maximum: 1050000
Mean: 389166.6666666667
Median: 302500.0
Standard deviation: 230322.53954448793
Variance: 53048472222.222206
25th percentile: 228750.0
50th percentile: 302500.0
75th percentile: 416250.0


Question 82: Store-Wise Standard Deviation
Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

In [76]:
store_std = np.std(sales_data, axis=1)
print("Bengaluru:", round(store_std[0], 2))
print("Hyderabad:", round(store_std[1], 2))
print("Chennai:", round(store_std[2], 2))
print("Mumbai:", round(store_std[3], 2))
print("Pune:", round(store_std[4], 2))

i = np.argmax(store_std)
print("Most variation:", stores[i])

Bengaluru: 223059.53
Hyderabad: 194502.57
Chennai: 249265.59
Mumbai: 271860.87
Pune: 177200.45
Most variation: Mumbai


Question 83: Category-Wise Standard Deviation
Determine which product category has the highest variation in sales across stores.

In [77]:
category_std = np.std(sales_data, axis=0)
print("Electronics:", round(category_std[0], 2))
print("Groceries:", round(category_std[1], 2))
print("Clothing:", round(category_std[2], 2))
print("Furniture:", round(category_std[3], 2))
print("Beauty:", round(category_std[4], 2))
print("Sports:", round(category_std[5], 2))

i = np.argmax(category_std)
print("Highest variation:", categories[i])

Electronics: 122539.79
Groceries: 43312.82
Clothing: 33911.65
Furniture: 41303.75
Beauty: 26570.66
Sports: 29832.87
Highest variation: Electronics


Question 84: Sales Above Company Average
Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

In [78]:
average_sales = np.mean(sales_data)
above_average = np.sum(sales_data > average_sales)
print("Company average sales:", average_sales)
print("Sales above average:", above_average)

Company average sales: 389166.6666666667
Sales above average: 10


Question 85: Outlier Detection
Treat any sales value greater than:

Mean + 1.5 × Standard Deviation
as a high-value outlier.

Identify all such sales values.

In [79]:
mean = np.mean(sales_data)
std = np.std(sales_data)
limit = mean + (1.5 * std)
outliers = sales_data[sales_data > limit]

print("Outlier limit:", limit)
print("High-value outliers:", outliers)

Outlier limit: 734650.4759833985
High-value outliers: [ 850000  780000  920000 1050000]


Part 15: Reshaping and Transformation
Question 86: Flatten Sales Data
Convert the two-dimensional sales array into a one-dimensional array using:

flatten()
ravel()
Explain the difference between the two methods.

In [80]:
flat_sales = sales_data.flatten()
ravel_sales = sales_data.ravel()
print("Using flatten():")
print(flat_sales)
print("Using ravel():")
print(ravel_sales)

Using flatten():
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
Using ravel():
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


Question 87: Reshape Sales Data
Reshape the 5 × 6 sales array into:

3 × 10
10 × 3
2 × 15
15 × 2
Verify that no data is lost.

In [81]:
a = sales_data.reshape(3, 10)
b = sales_data.reshape(10, 3)
c = sales_data.reshape(2, 15)
d = sales_data.reshape(15, 2)

print("3 x 10:\n", a)
print("10 x 3:\n", b)
print("2 x 15:\n", c)
print("15 x 2:\n", d)
print("Original values:", sales_data.size)
print("New values:", a.size)

3 x 10:
 [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
10 x 3:
 [[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
2 x 15:
 [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
15 x 2:
 [[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]
 [1050000  5100

Question 88: Transpose Sales Data
Transpose the sales array so that:

Rows represent product categories
Columns represent stores
Display the new shape.



In [82]:
new_sales = sales_data.T
print(new_sales)
print("New shape:", new_sales.shape)

[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
New shape: (6, 5)


Question 89: Combined Sales and Cost Array
Stack sales_data and cost_data vertically.

Display the resulting shape.

In [83]:
combined = np.vstack((sales_data, cost_data))
print(combined)
print("Shape:", combined.shape)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
Shape: (10, 6)


Question 90: Store-Level Combined Data
Create a three-dimensional array where:

First layer contains sales data
Second layer contains cost data
Use np.stack().

Display the shape of the new array.

In [84]:
combined_data = np.stack((sales_data, cost_data))
print(combined_data)
print("Shape:", combined_data.shape)

[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]
Shape: (2, 5, 6)


Part 16: Missing Data Scenario
The company discovers that some sales values were not recorded.

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
Question 91: Missing Value Detection
Find:

Total number of missing values
Location of missing values
Stores and categories containing missing values

In [8]:
missing = np.isnan(sales_with_missing)
print("Total missing:", np.sum(missing))
rows, cols = np.where(missing)
for row, col in zip(rows, cols):
    print("Store:", stores[row], "Category:", categories[col])

Total missing: 4
Store: Bengaluru Category: Clothing
Store: Hyderabad Category: Furniture
Store: Mumbai Category: Groceries
Store: Pune Category: Beauty


Question 92: Replace Missing Values with Zero
Replace all missing sales values with zero.

In [9]:
sales_with_missing[np.isnan(sales_with_missing)] = 0
print(sales_with_missing)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 93: Replace with Company Average
Replace missing values with the overall average of available sales values.

Use np.nanmean().

In [10]:
average = np.nanmean(sales_with_missing)
sales_with_missing[np.isnan(sales_with_missing)] = average

print(sales_with_missing)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 94: Replace with Category Average
Replace each missing value with the average sales value of its respective product category.

In [11]:
for col in range(sales_with_missing.shape[1]):
    average = np.nanmean(sales_with_missing[:, col])
    sales_with_missing[np.isnan(sales_with_missing[:, col]), col] = average
print(sales_with_missing)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 95: Missing Value Impact
Compare total sales before and after replacing missing values with zero.

In [12]:
before = np.nansum(sales_with_missing)
sales_zero = np.nan_to_num(sales_with_missing, nan=0)
after = np.sum(sales_zero)

print("Total sales before:", before)
print("Total sales after:", after)
print("Difference:", before - after)

Total sales before: 10370000.0
Total sales after: 10370000.0
Difference: 0.0


Part 17: Conditional Business Decisions
Question 96: Store Performance Labels
Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000
"Good": Total sales between ₹24,00,000 and ₹28,00,000
"Needs Improvement": Total sales below ₹24,00,000
Use np.select().

In [13]:
total_sales = np.sum(sales_data, axis=1)
conditions = [
    total_sales > 2800000,
    (total_sales >= 2400000) & (total_sales <= 2800000),
    total_sales < 2400000
]
labels = ["Excellent", "Good", "Needs Improvement"]
performance = np.select(conditions, labels)

for store, result in zip(stores, performance):
    print(store, ":", result)

Bengaluru : Needs Improvement
Hyderabad : Needs Improvement
Chennai : Needs Improvement
Mumbai : Excellent
Pune : Needs Improvement


Question 97: Profitability Classification
Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000
"Profitable": Profit between ₹1,00,000 and ₹2,00,000
"Low Profit": Profit below ₹1,00,000
"Loss": Profit below zero

In [20]:
conditions = [
    profit_data < 0,
    profit_data < 100000,
    profit_data <= 200000,
    profit_data > 200000
]

labels = [
    "Loss",
    "Low Profit",
    "Profitable",
    "Highly Profitable"
]

result = np.select(conditions, labels)
for i in range(len(stores)):
    for j in range(len(categories)):
        print(stores[i], categories[j], ":", result[i, j])

Bengaluru Electronics : Highly Profitable
Bengaluru Groceries : Profitable
Bengaluru Clothing : Low Profit
Bengaluru Furniture : Low Profit
Bengaluru Beauty : Low Profit
Bengaluru Sports : Low Profit
Hyderabad Electronics : Profitable
Hyderabad Groceries : Profitable
Hyderabad Clothing : Low Profit
Hyderabad Furniture : Low Profit
Hyderabad Beauty : Low Profit
Hyderabad Sports : Low Profit
Chennai Electronics : Highly Profitable
Chennai Groceries : Low Profit
Chennai Clothing : Low Profit
Chennai Furniture : Low Profit
Chennai Beauty : Low Profit
Chennai Sports : Low Profit
Mumbai Electronics : Highly Profitable
Mumbai Groceries : Profitable
Mumbai Clothing : Profitable
Mumbai Furniture : Low Profit
Mumbai Beauty : Low Profit
Mumbai Sports : Low Profit
Pune Electronics : Profitable
Pune Groceries : Low Profit
Pune Clothing : Low Profit
Pune Furniture : Low Profit
Pune Beauty : Low Profit
Pune Sports : Low Profit


Question 98: Expansion Recommendation
A store is eligible for expansion when:

Total sales are above ₹25,00,000
Total profit is above ₹7,00,000
Overall profit margin is above 25%
Identify eligible stores.

In [21]:
total_sales = np.sum(sales_data, axis=1)
total_profit = np.sum(profit_data, axis=1)
profit_margin = (total_profit / total_sales) * 100
eligible = (
    (total_sales > 2500000) &
    (total_profit > 700000) &
    (profit_margin > 25)
)

for i in range(len(stores)):
    if eligible[i]:
        print("Eligible for expansion:", stores[i])

Eligible for expansion: Mumbai


Question 99: Category Promotion Recommendation
A product category should receive additional promotion when:

Average sales are below ₹3,00,000
Profit margin is above 25%
Identify the categories that satisfy these conditions.

In [22]:
average_sales = np.mean(sales_data, axis=0)
total_profit = np.sum(profit_data, axis=0)
total_sales = np.sum(sales_data, axis=0)
profit_margin = (total_profit / total_sales) * 100
conditions = [
    average_sales < 300000,
    profit_margin > 25
]

result = conditions[0] & conditions[1]
for i in range(len(categories)):
    if result[i]:
        print("Promote:", categories[i])

Promote: Furniture
Promote: Beauty
Promote: Sports


Question 100: Cost Optimization Recommendation
Find store-category combinations where:

Cost is greater than ₹2,50,000
Profit margin is below 25%
These combinations should be reviewed for cost optimization.

In [23]:
profit_margin = (profit_data / sales_data) * 100
conditions = (
    (cost_data > 250000) &
    (profit_margin < 25)
)

for i in range(len(stores)):
    for j in range(len(categories)):
        if conditions[i, j]:
            print(
                "Store:", stores[i],
                "Category:", categories[j],
                "Cost:", cost_data[i, j],
                "Profit Margin:", round(profit_margin[i, j], 2), "%"
            )

Store: Bengaluru Category: Electronics Cost: 640000 Profit Margin: 24.71 %
Store: Hyderabad Category: Electronics Cost: 590000 Profit Margin: 24.36 %
Store: Hyderabad Category: Groceries Cost: 350000 Profit Margin: 23.91 %
Store: Chennai Category: Electronics Cost: 700000 Profit Margin: 23.91 %
Store: Chennai Category: Groceries Cost: 295000 Profit Margin: 24.36 %
Store: Mumbai Category: Electronics Cost: 790000 Profit Margin: 24.76 %
Store: Mumbai Category: Groceries Cost: 390000 Profit Margin: 23.53 %
Store: Pune Category: Electronics Cost: 530000 Profit Margin: 23.19 %
Store: Pune Category: Groceries Cost: 310000 Profit Margin: 23.46 %


Part 18: Inventory Scenario
Use the following inventory arrays:

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

In [24]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

Question 101: Closing Stock
Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold


In [25]:
closing_stock = opening_stock - units_sold
print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


Question 102: Low-Stock Identification
Identify store-category combinations where closing stock is below 30 units.

In [26]:
low_stock = closing_stock < 30
for i in range(len(stores)):
    for j in range(len(categories)):
        if low_stock[i, j]:
            print("Store:", stores[i], "Category:", categories[j], "Stock:", closing_stock[i, j])

Store: Bengaluru Category: Electronics Stock: 25
Store: Bengaluru Category: Furniture Stock: 25
Store: Hyderabad Category: Electronics Stock: 25
Store: Hyderabad Category: Furniture Stock: 25
Store: Chennai Category: Electronics Stock: 25
Store: Chennai Category: Furniture Stock: 25
Store: Mumbai Category: Electronics Stock: 25
Store: Pune Category: Electronics Stock: 25
Store: Pune Category: Furniture Stock: 20


Question 103: Stock Availability Percentage
Calculate the percentage of opening stock that remains unsold.

In [27]:
stock_percentage = (closing_stock / opening_stock) * 100
print(stock_percentage)

[[20.83333333 15.55555556 20.         27.77777778 24.         22.22222222]
 [22.72727273 16.         17.85714286 25.         22.22222222 22.5       ]
 [19.23076923 16.66666667 15.625      29.41176471 25.         23.52941176]
 [16.66666667 14.54545455 15.71428571 25.         21.66666667 20.45454545]
 [25.         17.5        21.15384615 26.66666667 25.         25.        ]]


Question 104: Fast-Moving Products
A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [28]:
sold_percentage = (units_sold / opening_stock) * 100
fast_moving = sold_percentage > 80
for i in range(len(stores)):
    for j in range(len(categories)):
        if fast_moving[i, j]:
            print("Store:", stores[i], "Category:", categories[j])

Store: Bengaluru Category: Groceries
Store: Hyderabad Category: Groceries
Store: Hyderabad Category: Clothing
Store: Chennai Category: Electronics
Store: Chennai Category: Groceries
Store: Chennai Category: Clothing
Store: Mumbai Category: Electronics
Store: Mumbai Category: Groceries
Store: Mumbai Category: Clothing
Store: Pune Category: Groceries


Question 105: Category-Wise Units Sold
Calculate the total units sold for each product category.

In [29]:
category_units_sold = np.sum(units_sold, axis=0)
for i in range(len(categories)):
    print(categories[i], ":", category_units_sold[i])

Electronics : 485
Groceries : 1950
Clothing : 1240
Furniture : 345
Beauty : 980
Sports : 720


Question 106: Store-Wise Units Sold
Calculate total units sold by each store.

In [30]:
store_units_sold = np.sum(units_sold, axis=1)
for i in range(len(stores)):
    print(stores[i], ":", store_units_sold[i])

Bengaluru : 1110
Hyderabad : 1175
Chennai : 1095
Mumbai : 1390
Pune : 950


Question 107: Best Store by Unit Sales
Identify the store that sold the highest total number of units.

In [31]:
best_store = np.argmax(store_units_sold)
print("Best store:", stores[best_store])
print("Units sold:", store_units_sold[best_store])

Best store: Mumbai
Units sold: 1390


 Question 108: Reorder Requirement

A store should reorder a category when closing stock is below 25 units.
Create a Boolean reorder matrix.
  

In [32]:
reorder = closing_stock < 25
print(reorder)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


Question 109: Reorder Quantity
Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [33]:
reorder_quantity = np.where(closing_stock < 25, 100 - closing_stock, 0)
print(reorder_quantity)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions
Question 110: Cumulative Store Sales
Calculate cumulative category sales for each store using np.cumsum().

In [34]:
cumulative_sales = np.cumsum(sales_data, axis=1)
print(cumulative_sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


Question 111: Cumulative Company Sales
Flatten the sales array and calculate cumulative company sales.



In [35]:
cumulative_sales = np.cumsum(sales_data.flatten())
print(cumulative_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


Question 112: Sales Difference Between Categories
Calculate the difference between consecutive category sales for each store using np.diff().

In [36]:
category_difference = np.diff(sales_data, axis=1)
print(category_difference)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


Question 113: Unique Sales Values
Find all unique sales values in sales_data.
Also count the frequency of each value.

In [37]:
unique_values, frequency = np.unique(sales_data, return_counts=True)
print("Unique sales values:", unique_values)
print("Frequency:", frequency)

Unique sales values: [ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]
Frequency: [1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1]


Question 114: Search for Specific Sales
Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [38]:
locations = np.argwhere(sales_data == 420000)
print("Locations:", locations)

Locations: [[0 1]]


Question 115: Compare Sales and Cost
Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all().

In [39]:
sales_greater_than_cost = sales_data > cost_data
print(sales_greater_than_cost)

all_profitable = np.all(sales_greater_than_cost)
print("All combinations profitable:", all_profitable)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
All combinations profitable: True


Question 116: Clip Profit Values
For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000
Maximum: ₹2,50,000
Use np.clip() to create a reporting profit array.

In [40]:
reporting_profit = np.clip(profit_data, 75000, 250000)
print(reporting_profit)

[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


Question 117: Normalize Sales Data
Normalize all sales values using min-max normalization:

Normalized Sales =
(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

In [41]:
minimum = np.min(sales_data)
maximum = np.max(sales_data)
normalized_sales = (sales_data - minimum) / (maximum - minimum)
print(normalized_sales)

[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


Question 118: Standardize Sales Data
Standardize sales using:

Standardized Sales =
(Sales - Mean Sales) / Standard Deviation


In [42]:
mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)
standardized_sales = (sales_data - mean_sales) / std_sales
print(standardized_sales)

[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


Question 119: Round Values
Convert profit margin values into:

Two decimal places
Nearest whole number
Floor values
Ceiling values

In [43]:
rounded_two = np.round(profit_margin, 2)
rounded_whole = np.round(profit_margin)
floor_values = np.floor(profit_margin)
ceiling_values = np.ceil(profit_margin)

print("Two decimal places:")
print(rounded_two)
print("Nearest whole number:")
print(rounded_whole)
print("Floor values:")
print(floor_values)
print("Ceiling values:")
print(ceiling_values)

Two decimal places:
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
Nearest whole number:
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]
Floor values:
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]
Ceiling values:
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


Question 120: Save and Load Data
Save the following arrays as NumPy binary files:

sales_data.npy
cost_data.npy
profit_data.npy
Load them back and verify that the loaded arrays are equal to the original arrays.

In [ ]:
np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)

sales_loaded = np.load("sales_data.npy")
cost_loaded = np.load("cost_data.npy")
profit_loaded = np.load("profit_data.npy")

print("Sales equal:", np.array_equal(sales_data, sales_loaded))
print("Cost equal:", np.array_equal(cost_data, cost_loaded))
print("Profit equal:", np.array_equal(profit_data, profit_loaded))


Sales equal: True
Cost equal: True
Profit equal: True
